version: '2'

networks:
  xuanxuan-net:
    driver: bridge


services:

# xuanxuan service
  xuanxuan:
    image: hub.qucheng.com/app/xuanxuan:${TAG}
    container_name: xuanxuan
    ports:
      - '8082:80'
      - '11444:11444'
    volumes:
      - 'xuanxuan_data:/data'
    environment:
      - DEBUG=true
    networks:
      - xuanxuan-net

# persistence for mysql and zdoo
volumes:
  xuanxuan_data:
    driver: local
