#!/bin/bash

# shellcheck disable=SC1091

. /opt/easysoft/scripts/libmysql.sh
. /etc/s6/s6-init/envs

[ -n "${DEBUG:+1}" ] && set -x

# Check and waiting mysql to be ready
wait_for_mysql || exit 1

/opt/zbox/run/php/php /opt/zbox/bin/zbox-docker.php start

exec /opt/zbox/run/xxd/xxd